# Generated by Django 2.2.3 on 2023-03-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pclog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('pc', models.CharField(max_length=255)),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.CharField(max_length=255)),
                ('app_name', models.CharField(max_length=255)),
                ('app_title', models.CharField(max_length=255)),
                ('open_time', models.DateTimeField()),
            ],
        ),
    ]
