# Generated by Django 2.2.3 on 2023-03-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_logstat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pclog',
            name='open_time',
            field=models.TimeField(),
        ),
    ]
